# fly.toml app configuration file generated for personal-finance-tracker-api on 2023-09-11T20:46:00-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "personal-finance-tracker-api"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
